

export const GET_PIZZAS = 'GET_PIZZAS'
export const SET_PIZZA_LOADED = 'SET_PIZZA_LOADED'
export const SET_ERROR_GET = 'SET_ERROR_GET'
export const TOGGLE_PIZZA = 'TOGGLE_PIZZA'
export const SET_SINGLE_PIZZA = 'SET_SINGLE_PIZZA'


export const INCREASE_PIZZA_QUANTITY = 'INCREASE_PIZZA_QUANTITY'
export const DECREASE_PIZZA_QUANTITY = 'DECREASE_PIZZA_QUANTITY'
export const REMOVE_PIZZA_ORDER = 'REMOVE_PIZZA_ORDER'
export const SEND_PIZZA_ORDER = 'SEND_PIZZA_ORDER'

export const SUCCESS_ORDER = 'SUCCESS_ORDER'